### ISSUE TITLE
Not work in 26.1.x

### ISSUE THREAD

**Issue by Mooling0602** [DerSimeon/JustEnoughPaper#2]
<img width="1358" height="396" alt="Image" src="https://github.com/user-attachments/assets/c57539fa-35a1-4763-a5cd-8c600fbee908" />

Error logs:

```fish
[Server]        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490) ~[?:?]
[Server]        ... 20 more
[Server] [16:23:21 INFO]: CleMooling joined the game
[Server] [16:23:21 INFO]: CleMooling[/218.64.220.101:56442] logged in with entity id 69 at ([minecraft:overworld]658.64256160372
[Server] [16:23:29 INFO]: CleMooling issued server command: /plugins
[Server] [16:25:05 INFO]: CleMooling lost connection: Disconnected
[Server] [16:25:05 INFO]: CleMooling left the game
[Server] [16:25:25 INFO]: UUID of player CleMooling is 392cdfd1-0016-4afa-ae13-66488ef79bb9
[Server] [16:25:26 ERROR]: Could not pass event PlayerJoinEvent to JustEnoughRecipes v1.2-SNAPSHOT
[Server] java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R7/CraftServer
[Server]        at JustEnoughRecipes-1.2-SNAPSHOT-reobf.jar//lol.simeon.jer.protocol.fabric.recipe.FabricRecipeEntryBuilder.buil
[Server]        at JustEnoughRecipes-1.2-SNAPSHOT-reobf.jar//lol.simeon.jer.listeners.ConnectionHandler.onJoin(ConnectionHandler
[Server]        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-26.1.2.build.5-alpha.jar:
[Server]        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:71) ~[paper-api-26.1.2.build.5-alpha.j
[Server]        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-26.1.2.jar:26.
[Server]        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-26.
[Server]        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-26.1.2.build.5-alph
[Server]        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:243) ~[paper-26.1.2.jar:26.1.2-5-d61d8
[Server]        at net.minecraft.server.network.config.PrepareSpawnTask$Ready.spawn(PrepareSpawnTask.java:319) ~[paper-26.1.2.jar:26.1.2-5-d61d8df]
[Server]        at net.minecraft.server.network.config.PrepareSpawnTask.spawnPlayer(PrepareSpawnTask.java:138) ~[paper-26.1.2.jar:26.1.2-5-d61d8df]
[Server]        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:205) ~[paper-26.1.2.jar:26.1.2-5-d61d8df]
[Server]        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-26.1.2.jar:26.1.2-5-d61d8df]
[Server]        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:8) ~[paper-26.1.2.jar:26.1.2-5-d61d8df]
[Server]        at net.minecraft.network.PacketProcessor$ListenerAndPacket.handle(PacketProcessor.java:99) ~[paper-26.1.2.jar:26.1.2-5-d61d8df]
[Server]        at net.minecraft.network.PacketProcessor.executeSinglePacket(PacketProcessor.java:33) ~[paper-26.1.2.jar:26.1.2-5-d61d8df]
[Server]        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1532) ~[paper-26.1.2.jar:26.1.2-5-d61d8df]
[Server]        at net.minecraft.server.MinecraftServer.recordTaskExecutionTimeWhileWaiting(MinecraftServer.java:1262) ~[paper-26.1.2.jar:26.1.2-5-d61d8df]
[Server]        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1378) ~[paper-26.1.2.jar:26.1.2-5-d61d8df]
[Server]        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:304) ~[paper-26.1.2.jar:26.1.2-5-d61d8df]
[Server]        at java.base/java.lang.Thread.run(Thread.java:1474) ~[?:?]
[Server] Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R7.CraftServer
[Server]        ... 20 more
```

**Comment by YimingZhanshen** [comment]
same problem in 26.1.2

[10:40:05] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to JustEnoughRecipes v1.2-SNAPSHOT
java.lang.IncompatibleClassChangeError: Found class net.minecraft.world.item.crafting.RecipeSerializer, but interface was expected
	at JustEnoughRecipes-1.2-SNAPSHOT-dev-all.jar//lol.simeon.jer.protocol.fabric.recipe.RecipeEntry.write(RecipeEntry.kt:23) ~[?:?]
	at net.minecraft.network.codec.StreamCodec$2.encode(StreamCodec.java:44) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at net.minecraft.network.codec.ByteBufCodecs$28.encode(ByteBufCodecs.java:532) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at net.minecraft.network.codec.ByteBufCodecs$28.encode(ByteBufCodecs.java:514) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at net.minecraft.network.codec.StreamCodec$4.encode(StreamCodec.java:78) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at JustEnoughRecipes-1.2-SNAPSHOT-dev-all.jar//lol.simeon.jer.protocol.fabric.FabricPacketBuilder.sendRecipeSyncAsDiscarded(FabricPacketBuilder.kt:23) ~[?:?]
	at JustEnoughRecipes-1.2-SNAPSHOT-dev-all.jar//lol.simeon.jer.listeners.ConnectionHandler.onJoin(ConnectionHandler.kt:29) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-26.1.2.build.2591-stable.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:71) ~[purpur-api-26.1.2.build.2591-stable.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-26.1.2.build.2591-stable.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:242) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at net.minecraft.server.network.config.PrepareSpawnTask$Ready.spawn(PrepareSpawnTask.java:312) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at net.minecraft.server.network.config.PrepareSpawnTask.spawnPlayer(PrepareSpawnTask.java:137) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:205) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:8) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at net.minecraft.network.PacketProcessor$ListenerAndPacket.handle(PacketProcessor.java:97) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at net.minecraft.network.PacketProcessor.executeSinglePacket(PacketProcessor.java:33) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1569) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at net.minecraft.server.MinecraftServer.recordTaskExecutionTimeWhileWaiting(MinecraftServer.java:1278) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1415) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:304) ~[purpur-26.1.2.jar:26.1.2-2591-bb69e15]
	at java.base/java.lang.Thread.run(Thread.java:1474) ~[?:?]

**Comment by LozoTrioxide** [comment]
Plugin crashes on PlayerJoinEvent when running on Paper 26.1.2:
```
Could not pass event PlayerJoinEvent to JustEnoughRecipes v1.2-SNAPSHOT
    at JustEnoughRecipes-1.2-SNAPSHOT-reobf.jar//lol.simeon.jer.protocol.fabric.recipe.FabricRecipeEntryBuilder.buildRecipeSyncEntries(FabricRecipeEntryBuilder.kt:11)
    at JustEnoughRecipes-1.2-SNAPSHOT-reobf.jar//lol.simeon.jer.listeners.ConnectionHandler.onJoin(ConnectionHandler.kt:26)
```
Plugin loads/enables cleanly, only fails at runtime when it touches NMS. Looks like it's a build-target mismatch rather than a logic bug, build.gradle.kts has:
```
paperweight.paperDevBundle("1.21.11-R0.1-SNAPSHOT")
minecraftVersion("1.21.11")
```
Since the reobf mapping table is version-locked, running the 1.21.11-targeted jar against 26.1.2 breaks the moment it casts Bukkit.getServer() as CraftServer. Bumping both of those to 26.1.2 and rebuilding should fix it.
